/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  'getAuditLogs' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getBatches' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCategories' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getCustomerOrders' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getCustomers' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getDrafts' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getInvoices' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getLowPriceAlertLogs' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getPayments' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getProducts' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getPurchaseOrders' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getReminderLogs' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getReminderRequests' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getReturns' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getSettings' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getShopUnits' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getTransactions' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUsers' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getVendorRateHistory' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getVendors' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'saveAuditLogs' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveBatches' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCategories' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCustomerOrders' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCustomers' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveDrafts' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveInvoices' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveLowPriceAlertLogs' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'savePayments' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveProducts' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'savePurchaseOrders' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveReminderLogs' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveReminderRequests' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveReturns' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveSettings' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveShopUnits' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveTransactions' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveUsers' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveVendorRateHistory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveVendors' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    'getAuditLogs' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getBatches' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCategories' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getCustomerOrders' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getCustomers' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getDrafts' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getInvoices' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getLowPriceAlertLogs' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getPayments' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getProducts' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getPurchaseOrders' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getReminderLogs' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getReminderRequests' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getReturns' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getSettings' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getShopUnits' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getTransactions' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUsers' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getVendorRateHistory' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getVendors' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'saveAuditLogs' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveBatches' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCategories' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCustomerOrders' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCustomers' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveDrafts' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveInvoices' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveLowPriceAlertLogs' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'savePayments' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveProducts' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'savePurchaseOrders' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveReminderLogs' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveReminderRequests' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveReturns' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveSettings' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveShopUnits' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveTransactions' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveUsers' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveVendorRateHistory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveVendors' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };