/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AddShopResult = IDL.Record({
  'shopId' : IDL.Text,
  'error' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});
export const DeleteShopResult = IDL.Record({ 'success' : IDL.Bool });
export const ActivityRecord = IDL.Record({
  'id' : IDL.Text,
  'activityType' : IDL.Text,
  'shopId' : IDL.Text,
  'metadata' : IDL.Text,
  'userId' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const AdminSettings = IDL.Record({
  'createdAt' : IDL.Int,
  'superAdminMobile' : IDL.Text,
  'updatedAt' : IDL.Int,
});
export const UserStatsResult = IDL.Record({
  'shopId' : IDL.Text,
  'totalSalesAmount' : IDL.Float64,
  'userId' : IDL.Text,
  'lastActivity' : IDL.Int,
  'isPaid' : IDL.Bool,
  'loginCount' : IDL.Nat,
  'shopName' : IDL.Text,
  'salesCount' : IDL.Nat,
});
export const BackupSnapshotMeta = IDL.Record({
  'id' : IDL.Text,
  'tag' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ShopStats = IDL.Record({
  'shopId' : IDL.Text,
  'sales' : IDL.Nat,
  'shopName' : IDL.Text,
  'profit' : IDL.Int,
  'transactions' : IDL.Nat,
  'products' : IDL.Nat,
  'customers' : IDL.Nat,
});
export const OwnerStats = IDL.Record({
  'totalProducts' : IDL.Nat,
  'totalProfit' : IDL.Int,
  'totalSales' : IDL.Nat,
  'totalCustomers' : IDL.Nat,
  'shopStats' : IDL.Vec(ShopStats),
  'totalTransactions' : IDL.Nat,
});
export const ShopMeta = IDL.Record({
  'id' : IDL.Text,
  'isDeleted' : IDL.Bool,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Text,
  'address' : IDL.Text,
  'ownerMobile' : IDL.Text,
});
export const ShopStatsResult = IDL.Record({
  'shopId' : IDL.Text,
  'totalSalesAmount' : IDL.Float64,
  'lastActivity' : IDL.Int,
  'shopName' : IDL.Text,
  'sessionCount' : IDL.Nat,
  'ownerMobile' : IDL.Text,
});
export const SuperAdminChangeLog = IDL.Record({
  'id' : IDL.Text,
  'fromMobile' : IDL.Text,
  'timestamp' : IDL.Int,
  'toMobile' : IDL.Text,
});
export const UpdateShopResult = IDL.Record({
  'error' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addShop' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [AddShopResult],
      [],
    ),
  'checkMobileExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'clearShopData' : IDL.Func([IDL.Text], [], []),
  'deleteBackupSnapshot' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteShop' : IDL.Func([IDL.Text], [DeleteShopResult], []),
  'findDuplicateUsers' : IDL.Func([], [IDL.Text], []),
  'getActivities' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Int), IDL.Opt(IDL.Int)],
      [IDL.Vec(ActivityRecord)],
      ['query'],
    ),
  'getAdminSettings' : IDL.Func([], [AdminSettings], ['query']),
  'getAllUsersWithStats' : IDL.Func(
      [IDL.Opt(IDL.Int), IDL.Opt(IDL.Int)],
      [IDL.Vec(UserStatsResult)],
      ['query'],
    ),
  'getAuditLogs' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getBackupSnapshotData' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getBackupSnapshots' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BackupSnapshotMeta)],
      ['query'],
    ),
  'getBatches' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCategories' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getCustomerOrders' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getCustomers' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getDrafts' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getFeedback' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getInvoices' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getLowPriceAlertLogs' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getMergeAuditLog' : IDL.Func([], [IDL.Text], ['query']),
  'getOwnerStats' : IDL.Func([IDL.Text], [OwnerStats], ['query']),
  'getPayments' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getProducts' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getPurchaseOrders' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getReferralCodes' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getReferralSignups' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getReminderLogs' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getReminderRequests' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getReturns' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getSettings' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getShop' : IDL.Func([IDL.Text], [IDL.Opt(ShopMeta)], ['query']),
  'getShopPerformanceStats' : IDL.Func(
      [IDL.Opt(IDL.Int), IDL.Opt(IDL.Int)],
      [IDL.Vec(ShopStatsResult)],
      ['query'],
    ),
  'getShopUnits' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getStaffAcrossShops' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getSuperAdminChangeLog' : IDL.Func(
      [],
      [IDL.Vec(SuperAdminChangeLog)],
      ['query'],
    ),
  'getSyncLogs' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getTransactions' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUsers' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getVendorRateHistory' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getVendors' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'initPermanentSuperAdmin' : IDL.Func([], [], []),
  'isPermanentSuperAdminQuery' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'listShopsForOwner' : IDL.Func([IDL.Text], [IDL.Vec(ShopMeta)], ['query']),
  'mergeUserAccounts' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'pruneOldBackups' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
  'purgeOldActivities' : IDL.Func([IDL.Int], [IDL.Nat], []),
  'recordActivity' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveAdminSettings' : IDL.Func([AdminSettings], [IDL.Bool], []),
  'saveAuditLogs' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveBackupSnapshot' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'saveBatches' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCategories' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCustomerOrders' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCustomers' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveDrafts' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveFeedback' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveInvoices' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveLowPriceAlertLogs' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'savePayments' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveProducts' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'savePurchaseOrders' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveReferralCodes' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveReferralSignups' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveReminderLogs' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveReminderRequests' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveReturns' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveSettings' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveShopUnits' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveSyncLog' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveTransactions' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveUsers' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveVendorRateHistory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveVendors' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'toggleUserPaidStatus' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'updateShop' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [UpdateShopResult],
      [],
    ),
  'verifyAndChangeSuperAdmin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AddShopResult = IDL.Record({
    'shopId' : IDL.Text,
    'error' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  const DeleteShopResult = IDL.Record({ 'success' : IDL.Bool });
  const ActivityRecord = IDL.Record({
    'id' : IDL.Text,
    'activityType' : IDL.Text,
    'shopId' : IDL.Text,
    'metadata' : IDL.Text,
    'userId' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const AdminSettings = IDL.Record({
    'createdAt' : IDL.Int,
    'superAdminMobile' : IDL.Text,
    'updatedAt' : IDL.Int,
  });
  const UserStatsResult = IDL.Record({
    'shopId' : IDL.Text,
    'totalSalesAmount' : IDL.Float64,
    'userId' : IDL.Text,
    'lastActivity' : IDL.Int,
    'isPaid' : IDL.Bool,
    'loginCount' : IDL.Nat,
    'shopName' : IDL.Text,
    'salesCount' : IDL.Nat,
  });
  const BackupSnapshotMeta = IDL.Record({
    'id' : IDL.Text,
    'tag' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ShopStats = IDL.Record({
    'shopId' : IDL.Text,
    'sales' : IDL.Nat,
    'shopName' : IDL.Text,
    'profit' : IDL.Int,
    'transactions' : IDL.Nat,
    'products' : IDL.Nat,
    'customers' : IDL.Nat,
  });
  const OwnerStats = IDL.Record({
    'totalProducts' : IDL.Nat,
    'totalProfit' : IDL.Int,
    'totalSales' : IDL.Nat,
    'totalCustomers' : IDL.Nat,
    'shopStats' : IDL.Vec(ShopStats),
    'totalTransactions' : IDL.Nat,
  });
  const ShopMeta = IDL.Record({
    'id' : IDL.Text,
    'isDeleted' : IDL.Bool,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Text,
    'address' : IDL.Text,
    'ownerMobile' : IDL.Text,
  });
  const ShopStatsResult = IDL.Record({
    'shopId' : IDL.Text,
    'totalSalesAmount' : IDL.Float64,
    'lastActivity' : IDL.Int,
    'shopName' : IDL.Text,
    'sessionCount' : IDL.Nat,
    'ownerMobile' : IDL.Text,
  });
  const SuperAdminChangeLog = IDL.Record({
    'id' : IDL.Text,
    'fromMobile' : IDL.Text,
    'timestamp' : IDL.Int,
    'toMobile' : IDL.Text,
  });
  const UpdateShopResult = IDL.Record({
    'error' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  
  return IDL.Service({
    'addShop' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [AddShopResult],
        [],
      ),
    'checkMobileExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'clearShopData' : IDL.Func([IDL.Text], [], []),
    'deleteBackupSnapshot' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteShop' : IDL.Func([IDL.Text], [DeleteShopResult], []),
    'findDuplicateUsers' : IDL.Func([], [IDL.Text], []),
    'getActivities' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Int), IDL.Opt(IDL.Int)],
        [IDL.Vec(ActivityRecord)],
        ['query'],
      ),
    'getAdminSettings' : IDL.Func([], [AdminSettings], ['query']),
    'getAllUsersWithStats' : IDL.Func(
        [IDL.Opt(IDL.Int), IDL.Opt(IDL.Int)],
        [IDL.Vec(UserStatsResult)],
        ['query'],
      ),
    'getAuditLogs' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getBackupSnapshotData' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getBackupSnapshots' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BackupSnapshotMeta)],
        ['query'],
      ),
    'getBatches' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCategories' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getCustomerOrders' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getCustomers' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getDrafts' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getFeedback' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getInvoices' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getLowPriceAlertLogs' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getMergeAuditLog' : IDL.Func([], [IDL.Text], ['query']),
    'getOwnerStats' : IDL.Func([IDL.Text], [OwnerStats], ['query']),
    'getPayments' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getProducts' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getPurchaseOrders' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getReferralCodes' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getReferralSignups' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getReminderLogs' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getReminderRequests' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getReturns' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getSettings' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getShop' : IDL.Func([IDL.Text], [IDL.Opt(ShopMeta)], ['query']),
    'getShopPerformanceStats' : IDL.Func(
        [IDL.Opt(IDL.Int), IDL.Opt(IDL.Int)],
        [IDL.Vec(ShopStatsResult)],
        ['query'],
      ),
    'getShopUnits' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getStaffAcrossShops' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getSuperAdminChangeLog' : IDL.Func(
        [],
        [IDL.Vec(SuperAdminChangeLog)],
        ['query'],
      ),
    'getSyncLogs' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getTransactions' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUsers' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getVendorRateHistory' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getVendors' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'initPermanentSuperAdmin' : IDL.Func([], [], []),
    'isPermanentSuperAdminQuery' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'listShopsForOwner' : IDL.Func([IDL.Text], [IDL.Vec(ShopMeta)], ['query']),
    'mergeUserAccounts' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'pruneOldBackups' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
    'purgeOldActivities' : IDL.Func([IDL.Int], [IDL.Nat], []),
    'recordActivity' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'saveAdminSettings' : IDL.Func([AdminSettings], [IDL.Bool], []),
    'saveAuditLogs' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveBackupSnapshot' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'saveBatches' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCategories' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCustomerOrders' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCustomers' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveDrafts' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveFeedback' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveInvoices' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveLowPriceAlertLogs' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'savePayments' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveProducts' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'savePurchaseOrders' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveReferralCodes' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveReferralSignups' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveReminderLogs' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveReminderRequests' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveReturns' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveSettings' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveShopUnits' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveSyncLog' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveTransactions' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveUsers' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveVendorRateHistory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveVendors' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'toggleUserPaidStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'updateShop' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [UpdateShopResult],
        [],
      ),
    'verifyAndChangeSuperAdmin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };