/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityRecord {
  'id' : string,
  'activityType' : string,
  'shopId' : string,
  'metadata' : string,
  'userId' : string,
  'timestamp' : bigint,
}
export interface AddShopResult {
  'shopId' : string,
  'error' : [] | [string],
  'success' : boolean,
}
export interface AdminSettings {
  'createdAt' : bigint,
  'superAdminMobile' : string,
  'updatedAt' : bigint,
}
export interface BackupSnapshotMeta {
  'id' : string,
  'tag' : string,
  'timestamp' : bigint,
}
export interface DeleteShopResult { 'success' : boolean }
export interface OwnerStats {
  'totalProducts' : bigint,
  'totalProfit' : bigint,
  'totalSales' : bigint,
  'totalCustomers' : bigint,
  'shopStats' : Array<ShopStats>,
  'totalTransactions' : bigint,
}
export interface ShopMeta {
  'id' : string,
  'isDeleted' : boolean,
  'city' : string,
  'name' : string,
  'createdAt' : string,
  'address' : string,
  'ownerMobile' : string,
}
export interface ShopStats {
  'shopId' : string,
  'sales' : bigint,
  'shopName' : string,
  'profit' : bigint,
  'transactions' : bigint,
  'products' : bigint,
  'customers' : bigint,
}
export interface ShopStatsResult {
  'shopId' : string,
  'totalSalesAmount' : number,
  'lastActivity' : bigint,
  'shopName' : string,
  'sessionCount' : bigint,
  'ownerMobile' : string,
}
export interface SuperAdminChangeLog {
  'id' : string,
  'fromMobile' : string,
  'timestamp' : bigint,
  'toMobile' : string,
}
export interface UpdateShopResult {
  'error' : [] | [string],
  'success' : boolean,
}
export interface UserProfile { 'name' : string }
export interface UserStatsResult {
  'shopId' : string,
  'totalSalesAmount' : number,
  'userId' : string,
  'lastActivity' : bigint,
  'isPaid' : boolean,
  'loginCount' : bigint,
  'shopName' : string,
  'salesCount' : bigint,
}
export interface _SERVICE {
  'addShop' : ActorMethod<[string, string, string, string], AddShopResult>,
  'checkMobileExists' : ActorMethod<[string], boolean>,
  'clearShopData' : ActorMethod<[string], undefined>,
  'deleteBackupSnapshot' : ActorMethod<[string, string], undefined>,
  'deleteShop' : ActorMethod<[string], DeleteShopResult>,
  'findDuplicateUsers' : ActorMethod<[], string>,
  'getActivities' : ActorMethod<
    [[] | [string], [] | [bigint], [] | [bigint]],
    Array<ActivityRecord>
  >,
  'getAdminSettings' : ActorMethod<[], AdminSettings>,
  'getAllUsersWithStats' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<UserStatsResult>
  >,
  'getAuditLogs' : ActorMethod<[string], string>,
  'getBackupSnapshotData' : ActorMethod<[string, string], [] | [string]>,
  'getBackupSnapshots' : ActorMethod<[string], Array<BackupSnapshotMeta>>,
  'getBatches' : ActorMethod<[string], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCategories' : ActorMethod<[string], string>,
  'getCustomerOrders' : ActorMethod<[string], string>,
  'getCustomers' : ActorMethod<[string], string>,
  'getDrafts' : ActorMethod<[string], string>,
  'getFeedback' : ActorMethod<[string], string>,
  'getInvoices' : ActorMethod<[string], string>,
  'getLowPriceAlertLogs' : ActorMethod<[string], string>,
  'getMergeAuditLog' : ActorMethod<[], string>,
  'getOwnerStats' : ActorMethod<[string], OwnerStats>,
  'getPayments' : ActorMethod<[string], string>,
  'getProducts' : ActorMethod<[string], string>,
  'getPurchaseOrders' : ActorMethod<[string], string>,
  'getReferralCodes' : ActorMethod<[string], string>,
  'getReferralSignups' : ActorMethod<[string], string>,
  'getReminderLogs' : ActorMethod<[string], string>,
  'getReminderRequests' : ActorMethod<[string], string>,
  'getReturns' : ActorMethod<[string], string>,
  'getSettings' : ActorMethod<[string], string>,
  'getShop' : ActorMethod<[string], [] | [ShopMeta]>,
  'getShopPerformanceStats' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<ShopStatsResult>
  >,
  'getShopUnits' : ActorMethod<[string], string>,
  'getStaffAcrossShops' : ActorMethod<[string], string>,
  'getSuperAdminChangeLog' : ActorMethod<[], Array<SuperAdminChangeLog>>,
  'getSyncLogs' : ActorMethod<[string], string>,
  'getTransactions' : ActorMethod<[string], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUsers' : ActorMethod<[string], string>,
  'getVendorRateHistory' : ActorMethod<[string], string>,
  'getVendors' : ActorMethod<[string], string>,
  'initPermanentSuperAdmin' : ActorMethod<[], undefined>,
  'isPermanentSuperAdminQuery' : ActorMethod<[string], boolean>,
  'listShopsForOwner' : ActorMethod<[string], Array<ShopMeta>>,
  'mergeUserAccounts' : ActorMethod<[string, string], string>,
  'pruneOldBackups' : ActorMethod<[string, bigint], bigint>,
  'purgeOldActivities' : ActorMethod<[bigint], bigint>,
  'recordActivity' : ActorMethod<[string, string, string, string], undefined>,
  'saveAdminSettings' : ActorMethod<[AdminSettings], boolean>,
  'saveAuditLogs' : ActorMethod<[string, string], undefined>,
  'saveBackupSnapshot' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'saveBatches' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCategories' : ActorMethod<[string, string], undefined>,
  'saveCustomerOrders' : ActorMethod<[string, string], undefined>,
  'saveCustomers' : ActorMethod<[string, string], undefined>,
  'saveDrafts' : ActorMethod<[string, string], undefined>,
  'saveFeedback' : ActorMethod<[string, string], undefined>,
  'saveInvoices' : ActorMethod<[string, string], undefined>,
  'saveLowPriceAlertLogs' : ActorMethod<[string, string], undefined>,
  'savePayments' : ActorMethod<[string, string], undefined>,
  'saveProducts' : ActorMethod<[string, string], undefined>,
  'savePurchaseOrders' : ActorMethod<[string, string], undefined>,
  'saveReferralCodes' : ActorMethod<[string, string], undefined>,
  'saveReferralSignups' : ActorMethod<[string, string], undefined>,
  'saveReminderLogs' : ActorMethod<[string, string], undefined>,
  'saveReminderRequests' : ActorMethod<[string, string], undefined>,
  'saveReturns' : ActorMethod<[string, string], undefined>,
  'saveSettings' : ActorMethod<[string, string], undefined>,
  'saveShopUnits' : ActorMethod<[string, string], undefined>,
  'saveSyncLog' : ActorMethod<[string, string], undefined>,
  'saveTransactions' : ActorMethod<[string, string], undefined>,
  'saveUsers' : ActorMethod<[string, string], undefined>,
  'saveVendorRateHistory' : ActorMethod<[string, string], undefined>,
  'saveVendors' : ActorMethod<[string, string], undefined>,
  'toggleUserPaidStatus' : ActorMethod<[string, string, boolean], boolean>,
  'updateShop' : ActorMethod<
    [string, string, string, string],
    UpdateShopResult
  >,
  'verifyAndChangeSuperAdmin' : ActorMethod<
    [string, string],
    { 'ok' : boolean, 'message' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];