/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface OwnerStats {
    totalProducts: bigint;
    totalProfit: bigint;
    totalSales: bigint;
    totalCustomers: bigint;
    shopStats: Array<ShopStats>;
    totalTransactions: bigint;
}
export interface BackupSnapshotMeta {
    id: string;
    tag: string;
    timestamp: bigint;
}
export interface ShopMeta {
    id: string;
    isDeleted: boolean;
    city: string;
    name: string;
    createdAt: string;
    address: string;
    ownerMobile: string;
}
export interface DeleteShopResult {
    success: boolean;
}
export interface ShopStats {
    shopId: string;
    sales: bigint;
    shopName: string;
    profit: bigint;
    transactions: bigint;
    products: bigint;
    customers: bigint;
}
export interface UpdateShopResult {
    error?: string;
    success: boolean;
}
export interface AdminSettings {
    createdAt: bigint;
    superAdminMobile: string;
    updatedAt: bigint;
}
export interface AddShopResult {
    shopId: string;
    error?: string;
    success: boolean;
}
export interface ActivityRecord {
    id: string;
    activityType: string;
    shopId: string;
    metadata: string;
    userId: string;
    timestamp: bigint;
}
export interface ShopStatsResult {
    shopId: string;
    totalSalesAmount: number;
    lastActivity: bigint;
    shopName: string;
    sessionCount: bigint;
    ownerMobile: string;
}
export interface UserProfile {
    name: string;
}
export interface UserStatsResult {
    shopId: string;
    totalSalesAmount: number;
    userId: string;
    lastActivity: bigint;
    isPaid: boolean;
    loginCount: bigint;
    shopName: string;
    salesCount: bigint;
}
export interface backendInterface {
    addShop(ownerMobile: string, shopName: string, address: string, city: string): Promise<AddShopResult>;
    clearShopData(shopId: string): Promise<void>;
    deleteBackupSnapshot(shopId: string, snapshotId: string): Promise<void>;
    deleteShop(shopId: string): Promise<DeleteShopResult>;
    getActivities(shopIdFilter: string | null, startTs: bigint | null, endTs: bigint | null): Promise<Array<ActivityRecord>>;
    getAdminSettings(): Promise<AdminSettings>;
    getAllUsersWithStats(startTs: bigint | null, endTs: bigint | null): Promise<Array<UserStatsResult>>;
    getAuditLogs(shopId: string): Promise<string>;
    getBackupSnapshotData(shopId: string, snapshotId: string): Promise<string | null>;
    getBackupSnapshots(shopId: string): Promise<Array<BackupSnapshotMeta>>;
    getBatches(shopId: string): Promise<string>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCategories(shopId: string): Promise<string>;
    getCustomerOrders(shopId: string): Promise<string>;
    getCustomers(shopId: string): Promise<string>;
    getDrafts(shopId: string): Promise<string>;
    getFeedback(shopId: string): Promise<string>;
    getInvoices(shopId: string): Promise<string>;
    getLowPriceAlertLogs(shopId: string): Promise<string>;
    getOwnerStats(mobile: string): Promise<OwnerStats>;
    getPayments(shopId: string): Promise<string>;
    getProducts(shopId: string): Promise<string>;
    getPurchaseOrders(shopId: string): Promise<string>;
    getReferralCodes(shopId: string): Promise<string>;
    getReferralSignups(shopId: string): Promise<string>;
    getReminderLogs(shopId: string): Promise<string>;
    getReminderRequests(shopId: string): Promise<string>;
    getReturns(shopId: string): Promise<string>;
    getSettings(shopId: string): Promise<string>;
    getShop(shopId: string): Promise<ShopMeta | null>;
    getShopPerformanceStats(startTs: bigint | null, endTs: bigint | null): Promise<Array<ShopStatsResult>>;
    getShopUnits(shopId: string): Promise<string>;
    getSyncLogs(shopId: string): Promise<string>;
    getTransactions(shopId: string): Promise<string>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUsers(shopId: string): Promise<string>;
    getVendorRateHistory(shopId: string): Promise<string>;
    getVendors(shopId: string): Promise<string>;
    listShopsForOwner(mobile: string): Promise<Array<ShopMeta>>;
    pruneOldBackups(shopId: string, retainDays: bigint): Promise<bigint>;
    purgeOldActivities(beforeTs: bigint): Promise<bigint>;
    recordActivity(shopId: string, userId: string, activityType: string, metadata: string): Promise<void>;
    saveAdminSettings(settings: AdminSettings): Promise<boolean>;
    saveAuditLogs(shopId: string, data: string): Promise<void>;
    saveBackupSnapshot(shopId: string, snapshotId: string, tag: string, data: string): Promise<void>;
    saveBatches(shopId: string, data: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveCategories(shopId: string, data: string): Promise<void>;
    saveCustomerOrders(shopId: string, data: string): Promise<void>;
    saveCustomers(shopId: string, data: string): Promise<void>;
    saveDrafts(shopId: string, data: string): Promise<void>;
    saveFeedback(shopId: string, data: string): Promise<void>;
    saveInvoices(shopId: string, data: string): Promise<void>;
    saveLowPriceAlertLogs(shopId: string, data: string): Promise<void>;
    savePayments(shopId: string, data: string): Promise<void>;
    saveProducts(shopId: string, data: string): Promise<void>;
    savePurchaseOrders(shopId: string, data: string): Promise<void>;
    saveReferralCodes(shopId: string, data: string): Promise<void>;
    saveReferralSignups(shopId: string, data: string): Promise<void>;
    saveReminderLogs(shopId: string, data: string): Promise<void>;
    saveReminderRequests(shopId: string, data: string): Promise<void>;
    saveReturns(shopId: string, data: string): Promise<void>;
    saveSettings(shopId: string, data: string): Promise<void>;
    saveShopUnits(shopId: string, data: string): Promise<void>;
    saveSyncLog(shopId: string, logEntry: string): Promise<void>;
    saveTransactions(shopId: string, data: string): Promise<void>;
    saveUsers(shopId: string, data: string): Promise<void>;
    saveVendorRateHistory(shopId: string, data: string): Promise<void>;
    saveVendors(shopId: string, data: string): Promise<void>;
    toggleUserPaidStatus(userId: string, shopId: string, isPaid: boolean): Promise<boolean>;
    updateShop(shopId: string, name: string, address: string, city: string): Promise<UpdateShopResult>;
}
import type { AddShopResult as _AddShopResult, ShopMeta as _ShopMeta, UpdateShopResult as _UpdateShopResult, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addShop(arg0: string, arg1: string, arg2: string, arg3: string): Promise<AddShopResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addShop(arg0, arg1, arg2, arg3);
                return from_candid_AddShopResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addShop(arg0, arg1, arg2, arg3);
            return from_candid_AddShopResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async clearShopData(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearShopData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearShopData(arg0);
            return result;
        }
    }
    async deleteBackupSnapshot(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBackupSnapshot(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBackupSnapshot(arg0, arg1);
            return result;
        }
    }
    async deleteShop(arg0: string): Promise<DeleteShopResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteShop(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteShop(arg0);
            return result;
        }
    }
    async getActivities(arg0: string | null, arg1: bigint | null, arg2: bigint | null): Promise<Array<ActivityRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivities(to_candid_opt_n4(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivities(to_candid_opt_n4(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async getAdminSettings(): Promise<AdminSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminSettings();
            return result;
        }
    }
    async getAllUsersWithStats(arg0: bigint | null, arg1: bigint | null): Promise<Array<UserStatsResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsersWithStats(to_candid_opt_n5(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsersWithStats(to_candid_opt_n5(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAuditLogs(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLogs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLogs(arg0);
            return result;
        }
    }
    async getBackupSnapshotData(arg0: string, arg1: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBackupSnapshotData(arg0, arg1);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBackupSnapshotData(arg0, arg1);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBackupSnapshots(arg0: string): Promise<Array<BackupSnapshotMeta>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBackupSnapshots(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBackupSnapshots(arg0);
            return result;
        }
    }
    async getBatches(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getBatches(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBatches(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategories(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories(arg0);
            return result;
        }
    }
    async getCustomerOrders(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerOrders(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerOrders(arg0);
            return result;
        }
    }
    async getCustomers(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomers(arg0);
            return result;
        }
    }
    async getDrafts(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getDrafts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDrafts(arg0);
            return result;
        }
    }
    async getFeedback(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedback(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedback(arg0);
            return result;
        }
    }
    async getInvoices(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoices(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoices(arg0);
            return result;
        }
    }
    async getLowPriceAlertLogs(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowPriceAlertLogs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowPriceAlertLogs(arg0);
            return result;
        }
    }
    async getOwnerStats(arg0: string): Promise<OwnerStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnerStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnerStats(arg0);
            return result;
        }
    }
    async getPayments(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayments(arg0);
            return result;
        }
    }
    async getProducts(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts(arg0);
            return result;
        }
    }
    async getPurchaseOrders(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getPurchaseOrders(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPurchaseOrders(arg0);
            return result;
        }
    }
    async getReferralCodes(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralCodes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralCodes(arg0);
            return result;
        }
    }
    async getReferralSignups(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralSignups(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralSignups(arg0);
            return result;
        }
    }
    async getReminderLogs(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getReminderLogs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReminderLogs(arg0);
            return result;
        }
    }
    async getReminderRequests(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getReminderRequests(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReminderRequests(arg0);
            return result;
        }
    }
    async getReturns(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getReturns(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReturns(arg0);
            return result;
        }
    }
    async getSettings(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings(arg0);
            return result;
        }
    }
    async getShop(arg0: string): Promise<ShopMeta | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getShop(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShop(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShopPerformanceStats(arg0: bigint | null, arg1: bigint | null): Promise<Array<ShopStatsResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShopPerformanceStats(to_candid_opt_n5(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShopPerformanceStats(to_candid_opt_n5(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getShopUnits(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getShopUnits(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShopUnits(arg0);
            return result;
        }
    }
    async getSyncLogs(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getSyncLogs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSyncLogs(arg0);
            return result;
        }
    }
    async getTransactions(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsers(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers(arg0);
            return result;
        }
    }
    async getVendorRateHistory(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getVendorRateHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVendorRateHistory(arg0);
            return result;
        }
    }
    async getVendors(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getVendors(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVendors(arg0);
            return result;
        }
    }
    async listShopsForOwner(arg0: string): Promise<Array<ShopMeta>> {
        if (this.processError) {
            try {
                const result = await this.actor.listShopsForOwner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listShopsForOwner(arg0);
            return result;
        }
    }
    async pruneOldBackups(arg0: string, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.pruneOldBackups(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pruneOldBackups(arg0, arg1);
            return result;
        }
    }
    async purgeOldActivities(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.purgeOldActivities(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purgeOldActivities(arg0);
            return result;
        }
    }
    async recordActivity(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordActivity(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordActivity(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async saveAdminSettings(arg0: AdminSettings): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAdminSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAdminSettings(arg0);
            return result;
        }
    }
    async saveAuditLogs(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAuditLogs(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAuditLogs(arg0, arg1);
            return result;
        }
    }
    async saveBackupSnapshot(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveBackupSnapshot(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveBackupSnapshot(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async saveBatches(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveBatches(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveBatches(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveCategories(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCategories(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCategories(arg0, arg1);
            return result;
        }
    }
    async saveCustomerOrders(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCustomerOrders(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCustomerOrders(arg0, arg1);
            return result;
        }
    }
    async saveCustomers(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCustomers(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCustomers(arg0, arg1);
            return result;
        }
    }
    async saveDrafts(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDrafts(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDrafts(arg0, arg1);
            return result;
        }
    }
    async saveFeedback(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveFeedback(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveFeedback(arg0, arg1);
            return result;
        }
    }
    async saveInvoices(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveInvoices(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveInvoices(arg0, arg1);
            return result;
        }
    }
    async saveLowPriceAlertLogs(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveLowPriceAlertLogs(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveLowPriceAlertLogs(arg0, arg1);
            return result;
        }
    }
    async savePayments(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePayments(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePayments(arg0, arg1);
            return result;
        }
    }
    async saveProducts(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProducts(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProducts(arg0, arg1);
            return result;
        }
    }
    async savePurchaseOrders(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePurchaseOrders(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePurchaseOrders(arg0, arg1);
            return result;
        }
    }
    async saveReferralCodes(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveReferralCodes(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveReferralCodes(arg0, arg1);
            return result;
        }
    }
    async saveReferralSignups(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveReferralSignups(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveReferralSignups(arg0, arg1);
            return result;
        }
    }
    async saveReminderLogs(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveReminderLogs(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveReminderLogs(arg0, arg1);
            return result;
        }
    }
    async saveReminderRequests(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveReminderRequests(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveReminderRequests(arg0, arg1);
            return result;
        }
    }
    async saveReturns(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveReturns(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveReturns(arg0, arg1);
            return result;
        }
    }
    async saveSettings(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSettings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSettings(arg0, arg1);
            return result;
        }
    }
    async saveShopUnits(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveShopUnits(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveShopUnits(arg0, arg1);
            return result;
        }
    }
    async saveSyncLog(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSyncLog(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSyncLog(arg0, arg1);
            return result;
        }
    }
    async saveTransactions(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTransactions(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTransactions(arg0, arg1);
            return result;
        }
    }
    async saveUsers(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveUsers(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveUsers(arg0, arg1);
            return result;
        }
    }
    async saveVendorRateHistory(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveVendorRateHistory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveVendorRateHistory(arg0, arg1);
            return result;
        }
    }
    async saveVendors(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveVendors(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveVendors(arg0, arg1);
            return result;
        }
    }
    async toggleUserPaidStatus(arg0: string, arg1: string, arg2: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleUserPaidStatus(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleUserPaidStatus(arg0, arg1, arg2);
            return result;
        }
    }
    async updateShop(arg0: string, arg1: string, arg2: string, arg3: string): Promise<UpdateShopResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShop(arg0, arg1, arg2, arg3);
                return from_candid_UpdateShopResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShop(arg0, arg1, arg2, arg3);
            return from_candid_UpdateShopResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AddShopResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AddShopResult): AddShopResult {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_UpdateShopResult_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UpdateShopResult): UpdateShopResult {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ShopMeta]): ShopMeta | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shopId: string;
    error: [] | [string];
    success: boolean;
}): {
    shopId: string;
    error?: string;
    success: boolean;
} {
    return {
        shopId: value.shopId,
        error: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.error)),
        success: value.success
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: [] | [string];
    success: boolean;
}): {
    error?: string;
    success: boolean;
} {
    return {
        error: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.error)),
        success: value.success
    };
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
